In [106]:
import pandas as pd

## Merge

`merge` extends data wider by joining data on a common column.

The join key is usually an id value, like a BBL for a land parcel.

In [15]:
work_on_stop_work_order = pd.read_csv('https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$query=SELECT%0A%20%20%60unique_key%60%2C%0A%20%20%60created_date%60%2C%0A%20%20%60closed_date%60%2C%0A%20%20%60agency%60%2C%0A%20%20%60agency_name%60%2C%0A%20%20%60complaint_type%60%2C%0A%20%20%60descriptor%60%2C%0A%20%20%60location_type%60%2C%0A%20%20%60incident_zip%60%2C%0A%20%20%60incident_address%60%2C%0A%20%20%60street_name%60%2C%0A%20%20%60cross_street_1%60%2C%0A%20%20%60cross_street_2%60%2C%0A%20%20%60intersection_street_1%60%2C%0A%20%20%60intersection_street_2%60%2C%0A%20%20%60address_type%60%2C%0A%20%20%60city%60%2C%0A%20%20%60landmark%60%2C%0A%20%20%60facility_type%60%2C%0A%20%20%60status%60%2C%0A%20%20%60due_date%60%2C%0A%20%20%60resolution_description%60%2C%0A%20%20%60resolution_action_updated_date%60%2C%0A%20%20%60community_board%60%2C%0A%20%20%60bbl%60%2C%0A%20%20%60borough%60%2C%0A%20%20%60x_coordinate_state_plane%60%2C%0A%20%20%60y_coordinate_state_plane%60%2C%0A%20%20%60open_data_channel_type%60%2C%0A%20%20%60park_facility_name%60%2C%0A%20%20%60park_borough%60%2C%0A%20%20%60vehicle_type%60%2C%0A%20%20%60taxi_company_borough%60%2C%0A%20%20%60taxi_pick_up_location%60%2C%0A%20%20%60bridge_highway_name%60%2C%0A%20%20%60bridge_highway_direction%60%2C%0A%20%20%60road_ramp%60%2C%0A%20%20%60bridge_highway_segment%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60location%60%0AWHERE%0A%20%20(%60agency%60%20%3D%3D%20%22DOB%22)%0A%20%20AND%20((%60created_date%60%20%3E%20%222025-01-01T00%3A00%3A00%22%20%3A%3A%20floating_timestamp)%0A%20%20%20%20%20%20%20%20%20AND%20(%60descriptor%60%20%3D%3D%20%22Working%20Contrary%20To%20Stop%20Work%20Order%22))%0AORDER%20BY%20%60created_date%60%20DESC%20NULL%20FIRST')

In [16]:
work_on_stop_work_order

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,64498896,2025-03-29T18:40:14.000,2025-03-29T18:40:14.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11378.0,58-15 BROWN PLACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.723878,-73.895711,"\n, \n(40.723877969051294, -73.89571091443487)"
1,64503451,2025-03-29T09:28:01.000,2025-03-29T09:28:01.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11217.0,323 BERGEN STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.682966,-73.980808,"\n, \n(40.68296621523423, -73.98080775945425)"
2,64486493,2025-03-28T14:38:32.000,2025-03-28T14:38:32.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11229.0,2603 AVENUE U,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.600038,-73.945516,"\n, \n(40.600037682748386, -73.9455160708741)"
3,64491604,2025-03-28T11:29:34.000,2025-03-28T11:29:34.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11219.0,1050 56 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.634377,-74.001629,"\n, \n(40.63437696235711, -74.0016285133211)"
4,64491521,2025-03-28T11:23:15.000,2025-03-28T11:23:15.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11230.0,957 EAST 5 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.628162,-73.972617,"\n, \n(40.62816225643836, -73.97261686436082)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,63596097,2025-01-02T13:46:48.000,2025-01-03T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11436.0,137-21 133 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.669161,-73.800100,"\n, \n(40.66916084793021, -73.80010010608537)"
444,63603648,2025-01-02T12:10:07.000,2025-01-03T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,10307.0,249 JOLINE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.506978,-74.235145,"\n, \n(40.50697752204665, -74.23514537300493)"
445,63598042,2025-01-02T11:45:49.000,2025-01-02T11:45:49.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11215.0,427 1 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.672206,-73.978554,"\n, \n(40.67220630285261, -73.97855415750168)"
446,63603731,2025-01-02T09:40:33.000,2025-01-06T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11420.0,133-38 130 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.669860,-73.809467,"\n, \n(40.66986019349893, -73.80946696653908)"
447,63592080,2025-01-01T05:34:06.000,2025-01-02T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11221.0,1058 JEFFERSON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.687703,-73.916778,"\n, \n(40.68770264648205, -73.91677842587687)"

In [18]:
(
    work_on_stop_work_order['bbl']
)

0      4.027770e+09
1               NaN
2      3.073310e+09
3      3.056880e+09
4      3.065030e+09
           ...
443    4.120750e+09
444    5.078120e+09
445    3.009660e+09
446    4.117880e+09
447    3.033870e+09
Name: bbl, Length: 448, dtype: float64

Download PLUTO from [Bytes of the Big Apple](https://s-media.nyc.gov/agencies/dcp/assets/files/zip/data-tools/bytes/pluto/nyc_pluto_25v1_csv.zip), unzip and move into the `Data/Source Data` folder.

In [50]:
pluto = pd.read_csv("../Data/Source Data/pluto_25v1.csv", low_memory=False)

Before merging datasets, it's a good idea to check that the keys in each dataset match those in the other:

In [53]:
(
    work_on_stop_work_order['bbl']
    .isin(pluto['bbl'])
    .all()
)

False

In [56]:
(
    work_on_stop_work_order
    [
        ~
        work_on_stop_work_order['bbl'].isin(pluto['bbl'])
    ]
    ['bbl']
)

1     NaN
76    NaN
96    NaN
108   NaN
122   NaN
201   NaN
204   NaN
214   NaN
251   NaN
284   NaN
307   NaN
319   NaN
355   NaN
381   NaN
397   NaN
420   NaN
Name: bbl, dtype: float64

In [57]:
(
    work_on_stop_work_order['bbl'].dropna()
    .isin(pluto['bbl'])
    .all()
)

True

If keys do not exactly match, use string manipulation tools (like `.str.replace()`, `.str.upper()`, `.str.split()` etc. to _normalize_ the labels between the two. This is an art as much as a science.)

Check for overlapping columns (by finding `intersection` of two sets of columns names)

In [78]:
set(work_on_stop_work_order.columns).intersection(set(pluto.columns))

{'bbl', 'borough', 'landmark', 'latitude', 'longitude'}

Column names that overlap and are not used for the merge are, by default, both kept but given the distinguishing suffixes `_x` and `_y`. 
Specifying `suffixes=` will apply custom suffixes to (only) the overlapping column names.

Use `validate` to ensure that keys are unique on one or both source tables. `1:1` checks that keys are unique on both sides (for an exact *one-to-one* merge). `m:1` checks that keys are unique on the right; these rows are broadcast to each matching row on the left: a *many-to-one* merge (`1:m` checks the opposite, for a one-to-many merge).

Using this validation argument avoid accidentally merging on non-unique keys.

In [80]:
work_on_stop_pluto = (
    work_on_stop_work_order
    .merge(
        pluto,
        on='bbl',
        how='inner',
        validate='m:1',
        suffixes=[None,'_pluto']
    )
)

alternatively, drop the overlapping columns from one or the other datasets before merge:

In [ ]:
# pluto_drop_borough = pluto.drop(columns=['borough'])

# (
#     work_on_stop_work_order
#     .drop(columns=['landmark','latitude','longitude'])
#     .merge(
#         pluto_drop_borough,
#         on='bbl',
#         how='inner',
#         validate='m:1',
#         suffixes=[None,'_pluto']
#     )
# )

In [87]:
work_on_stop_pluto

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,...,appbbl,appdate,plutomapid,firm07_flag,pfirm15_flag,version,dcpedited,latitude_pluto,longitude_pluto,notes
0,64498896,2025-03-29T18:40:14.000,2025-03-29T18:40:14.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11378.0,58-15 BROWN PLACE,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.723902,-73.895455,NaN
1,64486493,2025-03-28T14:38:32.000,2025-03-28T14:38:32.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11229.0,2603 AVENUE U,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.600282,-73.945487,NaN
2,64491604,2025-03-28T11:29:34.000,2025-03-28T11:29:34.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11219.0,1050 56 STREET,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.634146,-74.001690,NaN
3,64491521,2025-03-28T11:23:15.000,2025-03-28T11:23:15.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11230.0,957 EAST 5 STREET,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.628222,-73.972350,NaN
4,64492396,2025-03-28T11:20:14.000,2025-03-28T11:20:14.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11230.0,957 EAST 5 STREET,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.628222,-73.972350,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,63596097,2025-01-02T13:46:48.000,2025-01-03T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11436.0,137-21 133 AVENUE,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.669407,-73.799797,NaN
428,63603648,2025-01-02T12:10:07.000,2025-01-03T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,10307.0,249 JOLINE AVENUE,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.507022,-74.234933,NaN
429,63598042,2025-01-02T11:45:49.000,2025-01-02T11:45:49.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11215.0,427 1 STREET,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.672376,-73.978406,NaN
430,63603731,2025-01-02T09:40:33.000,2025-01-06T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11420.0,133-38 130 STREET,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.669252,-73.809981,NaN
431,63592080,2025-01-01T05:34:06.000,2025-01-02T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11221.0,1058 JEFFERSON AVENUE,...,NaN,NaN,1,NaN,NaN,25v1,NaN,40.687609,-73.916530,NaN

Once you have a merged DataFrame you can use combine columns from both sources for analysis:

In [84]:
(
    work_on_stop_pluto
    .groupby('borough')
    ['unique_key']
    .nunique()
)

borough
BRONX             37
BROOKLYN         236
MANHATTAN         49
QUEENS            89
STATEN ISLAND     21
Name: unique_key, dtype: int64

In [86]:
(
    work_on_stop_pluto
    .groupby('zonedist1')
    ['unique_key']
    .nunique()
    .sort_values(ascending=False)
    .head(5)
)

zonedist1
R5      53
R6B     46
R6      36
R7-1    33
R4      29
Name: unique_key, dtype: int64

If the matching key(s) have different column labels in the left and right tables, the key columns for each can be specified with `left_on` and `right_on` (or, if either has the matching key in an index, that can be specified with `left_index=True` or `right_index=True`)

Note:
- Merges will only link _exact_ matches between keys:
  - keys in `int` or `float` numeric types _are_ equivalent and will be matched.
  - but keys in numeric types will not be matched to `str` types. Cast one or the other column to a matching data type.
  - `str` keys will only match if they are _exact_ matches. Check for differences in capitalization, punctuation, etc. before merging on text keys (especially for data from different sources or that has been manually-entered).
  - datetime keys will match, but only to keys at the same detail (e.g. dates with dates, timestamps with timestamps). Resample datatime data to a common precision before merging.

the `.join()` method is an abbreviated form of the `.merge()` method which joins DataFrames on their indexes (only)

## concat

`concat` (concatenate) extends datasets longer by appending datasets together

E.g. litigation regarding Department of Corrections, published twice-annually by Law Department: https://www.nyc.gov/site/law/public-resources/nyc-administrative-code-7-113.page

In [89]:
doc_litigation_fy_20_24 = pd.read_excel('https://www.nyc.gov/assets/law/downloads/excel/DOC%20Alleged%20Misconduct%20Matters%20Commenced%20in%20FY%202020-2024.xls')
doc_litigation_cy_20_24 = pd.read_excel('https://www.nyc.gov/assets/law/downloads/excel/DOC%20Alleged%20Misconduct%20Matters%20Commenced%20in%20CY%202020-2024.xlsx')

In [90]:
doc_litigation_cy_20_24

,Matter Name,Plaintiff & Firm,Individual Defendants,Shield #,Represented by,Lit Start,Disp Date,Total City Payout AMT,Disp Group,Docket/ Index#,Court \n(Forum & Venue),Use of Force Alleged?,Assault/ Battery Alleged?
0,"ABAD, REBECCA VS CITY OF NEW YORK, ET AL.","Abad,Rebecca-NassRoper&Levin,PC",NaN,NaN,NaN,2021-04-22,NaT,0.0,NaN,712658/2020,Supreme Court - Queens,N,Y
1,"ABBAS, SAMIE VS TATE, JOHN DOE","Abbas,Samie-ProSe","Tate, Tiquon - Correction, Department of, NYC",NaN,"Karasyk & Moschella, LLP",2020-06-09,2022-03-29,0.0,Zero Disposition,20CV03636,U.S. District Court - Southern District NY,N,N
2,ABDELRAHMAN,"Abdelrahman,Salah-MichaelT.Ridge,Esq.",NaN,NaN,NaN,2022-09-20,2023-12-08,4500.0,Settlement,813729/2022E,Supreme Court - Bronx,N,N
3,"ABDUL-MUHAYMIN, IDRIS VS CITY OF NEW YORK, ET AL.","Abdul-Muhaymin,Idris-LawOfficeofK.E.Smith",NaN,NaN,NaN,2020-10-23,2022-03-25,9000.0,Settlement,032418/2020E,Supreme Court - Bronx,N,N
4,"ABEL-BEY, CHRISTOPHER VS CITY OF NEW YORK, ET AL.","Abel-Bey,Christopher-LawOfficesofDevonM.Radlin",NaN,NaN,NaN,2020-09-10,NaT,0.0,NaN,030127/2020E,Supreme Court - Bronx,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,LLP","Lue, Christopher - Correction, Department of, NYC",860.0,NaN,2021-08-24,NaT,0.0,NaN,809320/2021E,Supreme Court - Bronx,N,N
5528,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,LLP","LaTouche, Dennis - Correction, Department of, NYC",5315.0,NaN,2021-08-24,NaT,0.0,NaN,809320/2021E,Supreme Court - Bronx,N,N
5529,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Davis, John Doe - Correction, Department of, NYC",1282.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N
5530,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Jackson, Phillipe - Correction, Department of,...",13243.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N
5531,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Cohn, Eric - Correction, Department of, NYC",3701.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N

`pd.concat()` will align DataFrames on columns. If the DataFrames to combine have matching data fields in columns with different names (e.g. if you want to a column `Date` in the first DataFrame to be matched with a columns `month` in the second), use `.rename()` first to make hte column names match.

In [93]:
doc_litigation_fy_20_24.columns.equals(doc_litigation_cy_20_24.columns)

True

In [99]:
doc_litigation = pd.concat([
    doc_litigation_fy_20_24,
    doc_litigation_cy_20_24
])

In [94]:
doc_litigation

,Matter Name,Plaintiff & Firm,Individual Defendants,Shield #,Represented by,Lit Start,Disp Date,Total City Payout AMT,Disp Group,Docket/ Index#,Court \n(Forum & Venue),Use of Force Alleged?,Assault/ Battery Alleged?
0,"ABAD, REBECCA VS CITY OF NEW YORK, ET AL.","Abad,Rebecca-NassRoper&Levin,PC",NaN,NaN,NaN,2021-04-22,NaT,0.0,NaN,712658/2020,Supreme Court - Queens,N,N
1,"ABBAS, SAMIE VS TATE, JOHN DOE","Abbas,Samie-ProSe","Tate, Tiquon - Correction, Department of, NYC",NaN,"Karasyk & Moschella, LLP",2020-06-09,2022-03-29,0.0,Zero Disposition,20CV03636,U.S. District Court - Southern District NY,N,N
2,"ABDELRAHMAN, SALAH VS CITY OF NEW YORK","Abdelrahman,Salah-MichaelT.Ridge,Esq.",NaN,NaN,NaN,2022-09-20,2023-12-08,4500.0,Settlement,813729/2022E,Supreme Court - Bronx,N,N
3,"ABDUL-MUHAYMIN, IDRIS VS CITY OF NEW YORK, ET AL.","Abdul-Muhaymin,Idris-LawOfficeofK.E.Smith",NaN,NaN,NaN,2020-10-23,2022-03-25,9000.0,Settlement,032418/2020E,Supreme Court - Bronx,N,N
4,"ABEL-BEY, CHRISTOPHER VS CITY OF NEW YORK, ET AL.","Abel-Bey,Christopher-LawOfficesofDevonM.Radlin",NaN,NaN,NaN,2020-09-22,NaT,0.0,NaN,030663/2020E,Supreme Court - Bronx,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,LLP","Lue, Christopher - Correction, Department of, NYC",860.0,NaN,2021-08-24,NaT,0.0,NaN,809320/2021E,Supreme Court - Bronx,N,N
5528,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,LLP","LaTouche, Dennis - Correction, Department of, NYC",5315.0,NaN,2021-08-24,NaT,0.0,NaN,809320/2021E,Supreme Court - Bronx,N,N
5529,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Davis, John Doe - Correction, Department of, NYC",1282.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N
5530,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Jackson, Phillipe - Correction, Department of,...",13243.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N
5531,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Cohn, Eric - Correction, Department of, NYC",3701.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N

In [100]:
doc_litigation = (
    doc_litigation
    .drop_duplicates(
        keep='last'
    )
)

If data rows are overlapping across the concatenated sources, use `.drop_duplicates()` to remove duplicates. (include a `subset=` to drop only rows duplicated on that column)

In [101]:
doc_litigation

,Matter Name,Plaintiff & Firm,Individual Defendants,Shield #,Represented by,Lit Start,Disp Date,Total City Payout AMT,Disp Group,Docket/ Index#,Court \n(Forum & Venue),Use of Force Alleged?,Assault/ Battery Alleged?
0,"ABAD, REBECCA VS CITY OF NEW YORK, ET AL.","Abad,Rebecca-NassRoper&Levin,PC",NaN,NaN,NaN,2021-04-22,NaT,0.0,NaN,712658/2020,Supreme Court - Queens,N,N
2,"ABDELRAHMAN, SALAH VS CITY OF NEW YORK","Abdelrahman,Salah-MichaelT.Ridge,Esq.",NaN,NaN,NaN,2022-09-20,2023-12-08,4500.0,Settlement,813729/2022E,Supreme Court - Bronx,N,N
8,"ABOUBAKAR, OLALEKAN, ET AL VS CITY OF NEW YORK...","Aboubakar,Olalekan-GiskanSolotaroff&AndersonLL...",NaN,NaN,NaN,2020-04-08,NaT,0.0,NaN,20CV01716,U.S. District Court - Eastern District NY,N,N
9,"ABRACA, MIGUEL VS CITY OF NEW YORK, ET AL.","Abraca,Miguel-Sim&Depaola,LLP",NaN,NaN,NaN,2019-12-11,NaT,0.0,NaN,034420/2019E,Supreme Court - Bronx,N,N
13,"ABREU, HECTOR VS THE CITY OF NEW YORK, ET AL.","Abreu,Hector-Kaishian&MortazaviLLC","Newton, Joseph - Correction, Department of, NYC",18155.0,NaN,2024-03-05,NaT,0.0,NaN,801418/2024E,Supreme Court - Bronx,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,LLP","Lue, Christopher - Correction, Department of, NYC",860.0,NaN,2021-08-24,NaT,0.0,NaN,809320/2021E,Supreme Court - Bronx,N,N
5528,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,LLP","LaTouche, Dennis - Correction, Department of, NYC",5315.0,NaN,2021-08-24,NaT,0.0,NaN,809320/2021E,Supreme Court - Bronx,N,N
5529,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Davis, John Doe - Correction, Department of, NYC",1282.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N
5530,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Jackson, Phillipe - Correction, Department of,...",13243.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N
5531,"ZUBIDI, AMADO VS CITY OF NEW YORK, ET AL.","Zubidi,Amado-Jacobs&Hazan,PLLC","Cohn, Eric - Correction, Department of, NYC",3701.0,NaN,2022-11-01,NaT,0.0,NaN,814741/2022E,Supreme Court - Bronx,N,N

# Tasks

1. Which properties have the most construction incidents?
   1. Get dataset from DOB on [Construction-related incidents](https://data.cityofnewyork.us/Housing-Development/Construction-Related-Incidents/bf97-mjsy/about_data) 
   2. Summarize the number of incidents per property parcel.
   3. Merge these summary counts to PLUTO
   4. Show the address, council district, primary zoning district and number of incidents for 10 properties with the highest number of incidents. 
2. (extra credit) What are the address, council district, and primary zoning of the properties that have construction-related incidents and recent (within this calendar year) 311 complaints for work on a stop work order? 
   1. _hint: Merge two datasets, then merge a third to the merged result of the first merge._